_wandb:
    value:
        cli_version: 0.19.0
        m:
            - "1": predictions.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": data.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": predictions.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": predictions.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": predictions.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": predictions.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": predictions._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.19.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
learning_rate:
    value: 0.0001
mode:
    value: f
model:
    value: null
weight_decay:
    value: 0
